package edu.wctc;
import org.apache.commons.codec.language.Soundex;

public class LastNameUtility {
    private Soundex soundex = new Soundex();

    public String encodeLastName (String lastName) throws MissingNameException {
        if(lastName.isBlank()){
            throw new MissingNameException("last name");
        }
        // Returns the encoding of the last name generated by the Soundex algorithm
        return soundex.encode(lastName);
    }
}

